config/routes.rb
Rails.application.routes.draw do
  get 'search/users'
  devise_for :users,
    only: [:sessions, :registrations],
    controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
    }
  
  root "chats#index"
  resources :chats do
    resources :messages, only: [:create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages, -> { order(id: :asc) }, dependent: :destroy

  has_many :chat_memberships, inverse_of: :chat, dependent: :destroy
  has_many :members, through: :chat_memberships, source: :user

  class << self
    def chat_name_for(*users)
      users.map(&:id).sort.map {|id| "u#{id}" }.join("_")
    end

    def find_or_create_for(*users)
      raise AgrumentError, "At least 2 users." if users.size < 2
      name = chat_name_for(*users)
      self.create_with(members: users).create_or_find_by(name: name)
    end
  end
end

app/models/chat_membership.rb
class ChatMembership < ApplicationRecord
  belongs_to :user
  belongs_to :chat
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat, dependent: :destroy
  belongs_to :user

  after_create_commit do
    broadcast_append_to(
      chat,
      partial: "messages/message",
      locals: { message: self, current_user: nil },
      target: "messages"
    )
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :chat_memberships, inverse_of: :user, dependent: :destroy
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  attr_reader :chat
  alias current_chat chat

  helper_method :current_chat
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: %i[ show ]
  before_action :set_friends, only: %i[ index show ]

  def index
  end

  def show
    render action: :index
  end

  def create
    another_user = User.find(params[:user_id])
    chat = Chat.find_or_create_for(current_user, another_user)

    redirect_to chat
  end

  private
    def set_chat
      @chat = Chat.includes(:members).find(params[:id])
    end

    def set_friends
      @friends = User.where.not(id: current_user.id).all
    end

    def chat_params
      params.require(:chat).permit(:name)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_chat, only: %i[create]
  
  def create
    chat.messages.create(message_params.merge({ user: current_user }))

    render partial: "messages/form"
  end

  private

    def set_chat
      @chat = Chat.find(params[:chat_id])
    end

    def message_params
      params.require(:message).permit(:content)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def users
    @q = User.ransack(params[:q])

    @users = @q.result(distinct: true)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include LetterAvatar::AvatarHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
  def chat_friends(chat)
    chat.members.without(current_user)
  end

  def chat_name(chat)
    chat.members.without(current_user).map { |u| u.full_name }.join(",")
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/chats/_chat.html copy.erb
<div id="<%= dom_id chat %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= chat.name %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this chat", chat, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this chat", edit_chat_path(chat), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>


<li id="<%= dom_id chat %>">
  <%= link_to url, class: "group block rounded-lg p-1 text-center hover:bg-gray-100 dark:hover:bg-gray-600" do %>
    <div class="flex items-center gap-4">
      <%# <div class="relative items-center gap-4"> %>
        <%# <img class="h-8 w-8 rounded-full" src="<%= avatar_url " alt="" /> %>
        <%# <span class="<%= style(status:) "></span> %>
      <%# </div> %>
      <div class="font-medium dark:text-white">
        <div><%= chat.code %></div>
      </div>
    </div>
  <% end %>
</li>

app/views/chats/_chat.html.erb
<li id="<%= dom_id chat %>">
  <%= link_to chat_path(chat), class: "group block rounded-lg p-1 text-center hover:bg-gray-100 dark:hover:bg-gray-600" do %>
    <div class="flex items-center gap-4">
      <div class="font-medium dark:text-white">
        <div><%= chat.name %></div>
      </div>
    </div>
  <% end %>
</li>

app/views/chats/_chat_header.html.erb
<header class="flex-0">
  <nav class="border-gray-200 bg-white px-4 py-2.5 dark:bg-gray-800">
    <div class="flex flex-wrap items-center justify-between">
      <div class="flex items-center justify-start">
        <% if current_chat %>
          <button data-drawer-target="separator-sidebar" data-drawer-toggle="separator-sidebar" aria-controls="separator-sidebar" type="button" class="ms-3 mt-2 inline-flex items-center rounded-lg p-2 text-sm text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 sm:hidden dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600">
            <span class="sr-only">Open sidebar</span>
            <svg class="h-6 w-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path clip-rule="evenodd" fill-rule="evenodd" d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z"></path>
            </svg>
          </button>

          <div class="flex items-center gap-4">
            <div class="relative items-center gap-4">
              <div class="flex -space-x-4 rtl:space-x-reverse">
                <% chat_friends(current_chat).each do |user| %>
                  <img class="h-8 w-8 rounded-full" src="<%= letter_avatar_url(user.full_name, 100) %>" alt="<%= user.full_name %>">
                <% end %>
              </div>
              <%# <span class="absolute -left-1 -top-1 h-3.5 w-3.5 rounded-full border-2 border-white bg-green-400 dark:border-gray-800"></span> %>
            </div>

            <div class="font-medium dark:text-white">
              <div><%= chat_name(current_chat) %></div>
              <div class="text-sm text-gray-500 dark:text-gray-400">Active 3h ago</div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="flex items-center lg:order-2">
        <%= link_to destroy_user_session_path, data: { turbo_method: :delete } , class: "mr-1 rounded-lg p-2 text-gray-500 hover:bg-gray-100 hover:text-gray-900 focus:ring-4 focus:ring-gray-300 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white dark:focus:ring-gray-600", role: "menuitem" do %>
          <svg class="w-6 h-6 p-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 16">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 8h11m0 0-4-4m4 4-4 4m-5 3H3a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h3"/>
        </svg>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/chats/_form.html.erb
<%= form_with(model: chat, class: "contents") do |form| %>
  <% if chat.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
        <% chat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/chats/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing chat</h1>

  <%= render "form", chat: @chat %>

  <%= link_to "Show this chat", @chat, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to chats", chats_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/chats/index.html copy.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Chats</h1>
    <%= link_to "New chat", new_chat_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="chats" class="min-w-full">
    <%= render @chats %>
  </div>
</div>

<aside id="separator-sidebar" class="fixed left-0 top-0 z-40 h-screen w-64 -translate-x-full transition-transform sm:translate-x-0" aria-label="Sidebar">
  <div class="h-full overflow-y-auto bg-gray-50 px-3 py-4 dark:bg-gray-800">
    <ul class="space-y-2 border-gray-200 font-medium dark:border-gray-700">
      <li>
        <p class="text-2xl flex rounded-lg p-2 text-gray-900 transition duration-75 dark:text-white">Chats</p>
      </li>
      <li>
        <%= component Form::SearchUserForm %>
      </li>
      <% @chats.each do |chat| %>
        <%= component Data::UserListItem, url: chat_path(chat), name: chat.code, status: :online, avatar_url: "" %>
      <% end %>
    </ul>
  </div>
</aside>

app/views/chats/index.html.erb
<div class="flex h-screen w-screen">
  <aside id="separator-sidebar" class="fixed left-0  z-40 h-screen w-64 -translate-x-full transition-transform sm:translate-x-0" aria-label="Sidebar">
    <div class="h-full overflow-y-auto bg-gray-50 px-3 py-4 dark:bg-gray-800">
      <ul class="space-y-2 border-gray-200 font-medium dark:border-gray-700">
        <li>
          <p class="text-2xl flex rounded-lg p-2 text-gray-900 transition duration-75 dark:text-white">
            <%= image_tag "logo-1.png", class: "mr-2 h-8 rounded-full", alt: "Rails Messenger Logo" %>
            Chats
          </p>
        </li>
        <div id="friends" >
          <%= render partial: "users/friend", collection: @friends, as: :user %>
        </div>
      </ul>
    </div>
  </aside>

  <div class="flex h-screen w-screen flex-col justify-between sm:ml-64">
    <%= render partial: "chats/chat_header" %>
    <div class="flex flex-col space-y-4 p-3 overflow-y-scroll scrollbar-thumb-blue scrollbar-thumb-rounded scrollbar-track-blue-lighter scrollbar-w-2 scrolling-touch">
      <div class="scrollbar-thumb-blue scrollbar-thumb-rounded scrollbar-track-blue-lighter scrollbar-w-2 scrolling-touch flex flex-col space-y-4 overflow-y-auto p-3">
        <div id="messages" class="flex-col flex mr-4 flex-grow">
          <% if current_chat %>
            <%= turbo_stream_from current_chat %>
            <%= render current_chat.messages %>
          <% else %>  
            <div class="flex place-content-start items-start gap-2.5">
              <p class="py-2.5 text-sm font-normal text-gray-900">No Chat</p>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <%= render "messages/form" if current_chat  %>
  </div>
</div>

app/views/chats/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New chat</h1>

  <%= render "form", chat: @chat %>

  <%= link_to "Back to chats", chats_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/chats/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @chat %>

    <%= link_to "Edit this chat", edit_chat_path(@chat), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this chat", chat_path(@chat), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to chats", chats_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="dark">
  <head>
    <title>RailsMessenger</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" href="<%= image_url "logo.png" %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/messages/_form.html.erb
<turbo-frame id="<%= dom_id(current_chat, :form) %>">
<footer class="antialiased">
  <%= form_for [current_chat, Message.new] do |form| %>
    <%# <label for="chat" class="sr-only">Your message</label> %>
    <%= form.label :content, class: "sr-only" %>
    <div class="flex items-center bg-gray-50 px-3 py-2 dark:bg-gray-700">
      <%# <button type="button" class="inline-flex cursor-pointer justify-center rounded-lg p-2 text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-white">
        <svg class="h-5 w-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 18">
          <path fill="currentColor" d="M13 5.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0ZM7.565 7.423 4.5 14h11.518l-2.516-3.71L11 13 7.565 7.423Z" />
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18 1H2a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1Z" />
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 5.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0ZM7.565 7.423 4.5 14h11.518l-2.516-3.71L11 13 7.565 7.423Z" />
        </svg>
        <span class="sr-only">Upload image</span>
      </button>
      <button type="button" class="cursor-pointer rounded-lg p-2 text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-white">
        <svg class="h-5 w-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13.408 7.5h.01m-6.876 0h.01M19 10a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM4.6 11a5.5 5.5 0 0 0 10.81 0H4.6Z" />
        </svg>
        <span class="sr-only">Add emoji</span>
      </button> %>
      <%# <textarea id="chat" rows="1" class="mx-4 block w-full rounded-lg border border-gray-300 bg-white p-2.5 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-800 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500" placeholder="Your message..."></textarea> %>
      <%= form.text_field :content, class: "mx-4 block w-full rounded-lg border border-gray-300 bg-white p-2.5 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-800 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500", placeholder: "Your message..." %>
      <button type="submit" class="inline-flex cursor-pointer justify-center rounded-full p-2 text-blue-600 hover:bg-blue-100 dark:text-blue-500 dark:hover:bg-gray-600">
        <svg class="h-5 w-5 rotate-90 rtl:-rotate-90" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 18 20">
          <path d="m17.914 18.594-8-18a1 1 0 0 0-1.828 0l-8 18a1 1 0 0 0 1.157 1.376L8 18.281V9a1 1 0 0 1 2 0v9.281l6.758 1.689a1 1 0 0 0 1.156-1.376Z" />
        </svg>
        <span class="sr-only">Send message</span>
      </button>
    </div>
  <% end %>
</footer>

app/views/messages/_message.html.erb
<div id="<%= dom_id message %>">
  <div class="flex place-content-start items-start gap-2.5 py-1">
    <%# <img class="w-8 h-8 rounded-full" src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/bonnie-green.png" alt="Jese image"> %>
    <img class="h-8 w-8 rounded-full" src="<%= letter_avatar_url(message.user.full_name, 100) %>" alt="<%= message.user.full_name %>">
    <div class="leading-1.5 flex w-full max-w-[600px] flex-col rounded-lg px-3 border-gray-200 bg-gray-100 p-1 dark:bg-gray-700">
      <div class="flex items-center space-x-2 rtl:space-x-reverse">
        <span class="text-sm font-semibold text-gray-900 dark:text-white"><%= message.user.full_name %></span>
        <span class="text-sm font-normal text-gray-500 dark:text-gray-400"><%= message.created_at %></span>
      </div>
      <p class="py-2.5 text-sm font-normal text-gray-900 dark:text-white"><%= message.content %></p> 
    </div>
  </div>
</div>

app/views/messages/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Messages#create</h1>
  <p>Find me in app/views/messages/create.html.erb</p>
</div>

app/views/search/users.html.erb
<div>
  <h1 class="font-bold text-4xl">Search#users</h1>
  <p>Find me in app/views/search/users.html.erb</p>
</div>

app/views/users/_friend.html.erb
<li id="<%= dom_id user %>">
  <div class="flex items-center gap-4 group block rounded-lg p-1 text-center hover:bg-gray-100 dark:hover:bg-gray-600">
    <%= form_tag chats_path, method: :post, class: "flex  w-full" do %>
      <%= hidden_field_tag :user_id, user.id %>
        <%= letter_avatar_tag(user.full_name, 100, class: 'h-8 w-8 rounded-full') %>
        <span class="bg-green-400"></span>

        <%= button_tag type: :submit do %>
          <div class="flex items-center gap-4 px-2">
            <div class="font-medium dark:text-white">
              <div><%= user.full_name %></div>
            </div>
          </div>
        <% end %>
    <% end %>
  </div>
</li>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false" class="text-gray-500">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>